/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:988863ba-ba69-4f04-9027-97ad167c3ff3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_MdgM9vm90",
    "aws_user_pools_web_client_id": "5q1n8od7tng1mr8fkbjgu3nb5u",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://a6qnphz2v5c4xkwiz5yjczm5qy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vehiem7enffjvarvtj7nejnyw4",
    "aws_user_files_s3_bucket": "financetrackingeeacfad5957e4e949252b0ef0423e8b7213030-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
